```{r}
library(tidyverse)
library(rstan)
#library(R2jags)
library(HDInterval)
```

```{r}
ayuda2 <- c(32,35,36)
dengue <- dengue[1:1000,]

for (i in ayuda2) {
  print(names(dengue)[i])
  # Tabla de contingencia entre las variables 
tabla_contingencia <- table(dengue$clas_dengue, dengue[,i])

# Prueba de independencia (chi-cuadrado)
resultado <- chisq.test(tabla_contingencia)

print(resultado$p.value)
}
```

```{r}
x6 <- as.factor(dengue2[,ayuda2[1]])
x7 <- as.factor(dengue2[,ayuda2[2]])
x8 <- as.factor(dengue2[,ayuda2[3]])
#x9 <- as.factor(dengue2[,ayuda2[4]])
```


```{r}
X <- model.matrix(~x6 + x7 + x8)
 
 stan_data <- list(
  
  "X" = X,
  
  "y" = y,
  
  "N" = nrow(dengue2), # Numero de observaciones
  "p" = ncol(X) # numero de variables
)

  
 fit2 <- stan(file = 'Parte.stan', data = stan_data, chains = 3, iter = 8000,warmup = 4000)
 
```

# HDI para los coeficientes

```{r}
Beta.poste2 <- as.data.frame(fit2, "beta")

for(i in 1:dim(Beta.poste2)[2]){
  nombre_archivo <- paste0("Graficos2/HDI/graf", i, ".jpg")
  jpeg(nombre_archivo, width = 800, height = 600)
  #Inicio
  HDI.interval.beta <- hdi(Beta.poste2[,i])
  value1 <- HDI.interval.beta[1]
  value2 <- HDI.interval.beta[2]
  DENSITITY.BETA <- density(Beta.poste2[,i])
  plot(DENSITITY.BETA, main = "Densidad Posterior", xlab = parse(text=(paste0("beta[",i,"]"))))
  DENSITITY.BETAy <- DENSITITY.BETA$y
  DENSITITY.BETAx <- DENSITITY.BETA$x
  # Lower and higher indices on the X-axis
  l <- min(which(DENSITITY.BETAx >= value1))
  h <- max(which(DENSITITY.BETAx < value2))
  
  polygon(c(DENSITITY.BETAx[c(l, l:h, h)]),
          c(0, DENSITITY.BETAy[l:h], 0),
          col = "slateblue1")
  #Fin
  dev.off()
}
```

# Traceplots

```{r}
jpeg("Graficos2/TRACEPLOT/traceplot.jpg", width = 800, height = 600)
traceplot(fit2)
dev.off()
```


# ACF

```{r}
betas2 = extract(fit2, pars = "beta")

for (i in 1:6){
  nombre_archivo <- paste0("Graficos2/ACF/graf", i, ".jpg")
  jpeg(nombre_archivo, width = 800, height = 600)
  
  #DIAGNOSTICOS
  #GRAFICOS: FUNCION DE AUTOCORRELACION
  acf(betas2[[1]][,i])
  
  dev.off()
}
```

#GRAFICO DE LA DENSIDAD POSTERIOR

```{r}
for (i in 1:6){
  nombre_archivo <- paste0("Graficos2/DENSIDAD/graf", i, ".jpg")
  jpeg(nombre_archivo, width = 800, height = 600)
  plot(density(betas2[[1]][,i]))
  
  dev.off()
}
```


# Curva roc

```{r}
library(pROC)
# Obtener los coeficientes del modelo
# Extraer los coeficientes del modelo
# Extraer las muestras generadas
samples <- extract(fit2)
# Calcular la media de las muestras
# Convertir el vector en una matriz de una columna
media_coeficientes <- colMeans(samples$beta)
coeficientes <- matrix(media_coeficientes, ncol = 1)







# Obtener la matriz de dise침o X
X8 <- model.matrix(y ~ x6 + x7 + x8 + x9 + x10, data = dengue2)

# Calcular las probabilidades predichas
predicciones <- plogis(X8 %*% coeficientes)

# Calcular la curva ROC
curva_roc <- roc(y, predicciones)
```

```{r}
auc(curva_roc)
```


```{r}
jpeg("Graficos2/ROC/curva.jpg", width = 800, height = 600)
plot(curva_roc,main = "Modelo 2")
dev.off()
```



# ACF

```{r}
betas2 = extract(fit2, pars = "beta")

jpeg("Graficos2/ACF/unido.jpg", width = 800, height = 600)
par(mfrow = c(2,3))

acf(betas2[[1]][,1])
acf(betas2[[1]][,2])
acf(betas2[[1]][,3])
acf(betas2[[1]][,4])
acf(betas2[[1]][,5])
acf(betas2[[1]][,6])
dev.off()
  
```

#GRAFICO DE LA DENSIDAD POSTERIOR

```{r}
jpeg("Graficos2/DENSIDAD/unido.jpg", width = 800, height = 600)
par(mfrow = c(2,3))
plot(density(betas2[[1]][,1]))
plot(density(betas2[[1]][,2]))
plot(density(betas2[[1]][,3]))
plot(density(betas2[[1]][,4]))
plot(density(betas2[[1]][,5]))
plot(density(betas2[[1]][,6]))
dev.off()
 
```


```{r}
Beta.poste2 <- as.data.frame(fit2, "beta")

jpeg("Graficos2/HDI/unido.jpg", width = 800, height = 600)
par(mfrow = c(2,3))

for(i in 1:dim(Beta.poste2)[2]){
  #Inicio
  HDI.interval.beta <- hdi(Beta.poste2[,i])
  value1 <- HDI.interval.beta[1]
  value2 <- HDI.interval.beta[2]
  DENSITITY.BETA <- density(Beta.poste2[,i])
  plot(DENSITITY.BETA, main = "Densidad Posterior", xlab = parse(text=(paste0("beta[",i,"]"))))
  DENSITITY.BETAy <- DENSITITY.BETA$y
  DENSITITY.BETAx <- DENSITITY.BETA$x
  # Lower and higher indices on the X-axis
  l <- min(which(DENSITITY.BETAx >= value1))
  h <- max(which(DENSITITY.BETAx < value2))
  
  polygon(c(DENSITITY.BETAx[c(l, l:h, h)]),
          c(0, DENSITITY.BETAy[l:h], 0),
          col = "slateblue1")
  #Fin
}
dev.off()
```

```{r}
library(loo)
# C치lculo de las estimaciones LOO
loo1 <- loo(fit)
loo2 <- loo(fit2)

# Comparaci칩n de los modelos
compare_models <- compare(loo1, loo2)

# Resumen de la comparaci칩n
print(compare_models)
```

